### ISSUE TITLE
FR: Dark theme

### ISSUE THREAD

**Issue by myhrmans** [cristianpb/muse#14]
Would be really nice to have a way to customize the colors in the frontend, and maybe a theme selection where a dark theme could be choosed.

**Comment by cristianpb** [comment]
Hi @myhrmans 
Thanks for you message, I'm working in a dark theme, could you please test if dark theme works well for you, you can find dev version here: https://cristianpb.github.io/muse/

Thanks

**Comment by cristianpb** [comment]
There is now a Dark theme available from version v.0.0.18, this follows your browser dark theme configuration.
