### ISSUE TITLE
Qustion: How to get local files in the search?

### ISSUE THREAD

**Issue by sprnza** [cristianpb/muse#16]
Hi there!
I've added a local music library to mopidy:
```
[file] 
enabled = true 
media_dirs = 
    /mnt/data/Music|Music 
show_dotfiles = false 
excluded_file_extensions = 
  .directory 
  .html 
  .jpeg 
  .jpg 
  .log 
  .nfo 
  .pdf 
  .png 
  .txt 
  .zip 
follow_symlinks = false 
metadata_timeout = 1000
```
But I don't have anything related to "local" or "files" in search sources. Is it possible to search through local files also?

**Comment by cristianpb** [comment]
Hi,

You need to install [Mopidy-Local extension](https://mopidy.com/ext/local/) and then scan your media library using the command `mopidy local scan`. At the end you will be able to browser and also search in your local files using Muse :) 

![image](https://user-images.githubusercontent.com/18708179/92152431-efeff280-ee22-11ea-9ee0-92380af9db81.png)

**Comment by sprnza** [comment]
Thanks!
