### ISSUE TITLE
On mobile view mute buttons aren't visible

### ISSUE THREAD

**Issue by sprnza** [cristianpb/muse#18]
Hi there!
On mobile view mute buttons aren't visible nothing to add actually! )
Thanks for the project I use it every day! ))

**Comment by sprnza** [comment]
I mean the mute buttons of snapcast clients

**Comment by cristianpb** [comment]
Hi
There are some mobile devices that have few horizontal space, so I decided to remove it. But I think I will add them in the next release. I want also to made some modifications to the window where you can modify snapcast clients.
And thanks for your message. I'm glad that you like Muse 😊

**Comment by cristianpb** [comment]
Hi!
Relase 0.0.21 is out with mute buttons for clients in mobile version 🚀 
I think I will do something to avoid problems when there are a lot of clients but that would have to be in another issue 🍿

**Comment by sprnza** [comment]
Thanks!
