### ISSUE TITLE
Search returns nothing if nothing found in the first search provider

### ISSUE THREAD

**Issue by sprnza** [cristianpb/muse#22]
I've got "File" search provider placed first in the list. And with it selected search returns nothing all the time (I don't have it set up). If I deselect it, the search becomes working.

**Comment by cristianpb** [comment]
Mopidy-file allows you to browser your music without indexing your files however in doesn't allow searching.

https://discourse.mopidy.com/t/what-exactly-is-the-difference-between-extensions-local-and-file/1073

I will disable it by default in the search sources to avoid this kind of confusions.

**Comment by sprnza** [comment]
Ah, I see! Thanks! I'll disable Mopidy-File as soon as I don't use it.
