### ISSUE TITLE
Tunein "Now Playing" song info does not update

### ISSUE THREAD

**Issue by tekdru** [cristianpb/muse#23]
When I play a TuneIn station or add a station to the play queue, the station initially plays fine with the accurate song info.  I notice that after the actual audio changes to a new song, the song information that is displayed in "Now Playing" remains the same as what was originally playing at the time that the station was added to the "Now Playing" queue and never changes or updates to the current song info.

I see that the song info is updated properly if I switch to the Musicbox webclient but its not updated in the IRIS or Muse webclients

![Screen Shot 2020-10-29 at 1 59 41 PM](https://user-images.githubusercontent.com/7363668/97613634-4aef3180-19ef-11eb-925b-f85ae297910c.png)
![Screen Shot 2020-10-29 at 1 59 27 PM](https://user-images.githubusercontent.com/7363668/97613644-4fb3e580-19ef-11eb-86c3-9cb0efa860cd.png)
![Screen Shot 2020-10-29 at 2 00 02 PM](https://user-images.githubusercontent.com/7363668/97613651-52163f80-19ef-11eb-998e-099c202ea946.png)

**Comment by cristianpb** [comment]
Hi,
You are completely right. I gotta add this too. Should be nice to have the album art for tuneIn  📻 stations

**Comment by tekdru** [comment]
Thanks. Yes that would be cool!

**Comment by cristianpb** [comment]
This should work in version 0.0.23
I will close this issue, but feel free to reopen if it's not the case.

**Comment by tekdru** [comment]
I'm running version 0.0.24 now but the song info from radio station still does not update. It only shows the first song at the time the station was added to the playlist.

![Screen Shot 2021-01-04 at 12 35 16 PM](https://user-images.githubusercontent.com/7363668/103562581-521c3b00-4e89-11eb-8be9-e81b5136d70a.png)
