### ISSUE TITLE
How to get snapcast control working?

### ISSUE THREAD

**Issue by klundry** [cristianpb/muse#4]
Is there a configuration setting needed to get snapcast control working? I'm not seeing anything obvious and I don't see anywhere to select different snapclients.

**Comment by cristianpb** [comment]
Hi @klundry 
The interface searchs for the snapcast controlling service at the url of the interface at http port 1780. After connection it will automatically show an icon at the bottom navigation bar.

So for example if you have installed snapcast in a raspberry pi that has the ip `192.168.1.1`, then it will automatically search for a snapcast service at `192.168.1.1:1780`

Can you tell me more about where did you installed snapcast ? 

Maybe it depends on the snapcast version that you have. I remember that the default version of raspbian buster didn't have the controlling service at 1780.

**Comment by klundry** [comment]
Ah, that is likely the issue. I have snapcast running on the same board but a different port. Would it be possible to add the ability to specify your port in the config? Might be nice if you already have a bunch of snapcast clients setup on a different port.

**Comment by cristianpb** [comment]
I added a settings page (you can access in the top navigation bar) where you can modify the hostname and port for snapcast.

It's on the version `0.0.12`. You can upgrade using `python3 -m pip install --upgrade Mopidy-Muse`

Would you mind to try and tell me if it works ?

**Comment by klundry** [comment]
I can see the settings page, but when I change the port and hit connect I get just a continuously spinning dots.

**Comment by cristianpb** [comment]
I'm not sure if it's the snapcast version. I use a websocket connection, which seems to be available since version 0.16.0. https://github.com/badaix/snapcast/releases/tag/v0.16.0

Do you have this version ? `snapserver --version` ?

**Comment by klundry** [comment]
Wow, didn't realize my snapserver was so behind. Turns out 0.15 is the newest version available as a .deb for aarch64 which is what my server is. Looks like I will have to build from source to get up to date. I'll get back to you when I get that upgraded and test.

**Comment by cristianpb** [comment]
It happen to me too, in raspbian buster the default package is 0.15

If you are on debian or raspbian, you don't have to compile from source. You can get the `*.deb` package from the releases page: https://github.com/badaix/snapcast/releases/tag/v0.19.0

**Comment by klundry** [comment]
I tried that first with the armhf deb and it installs without errors but I cannot get snapserver to start. I get an "illegal instruction" error. 

I guess I can't build from source either because the external submodules are on git.xiph.org but git.xiph.org is down :-/.

**Comment by cristianpb** [comment]
I checked my logs and I didn't have any problem with the `.deb` version in buster. I just installed with `dpkg` and then I started the service with `systemctl`.

**Comment by klundry** [comment]
I haven't had any trouble with that method either before now. I think my board running aarch64 armbian is the issue. The armhf packages are for 32bit. Compiling is no problem as long as the got repos I need actually work.

**Comment by klundry** [comment]
An update: the xiph git repos have just moved and one of the submodules was missing a couple of commits so it fails when trying to clone. The fixes should be pushed to master soon and then I'll be able to finally compile a newer version of snapserver and test this :).

**Comment by cristianpb** [comment]
Thank you for the update. I added some small modifications to the snapcast connection settings that will be available in the next release.

**Comment by cristianpb** [comment]
Hi, I just added an option to connect to snapcast using ssl. Any news about your tests ?

**Comment by klundry** [comment]
No updates yet. Snapcast still has pushed out the new release with the fixes.

**Comment by klundry** [comment]
Alright, finally got the latest version of snapserver installed and the volume control is working great. Thanks!

**Comment by cristianpb** [comment]
Nice to hear that it works! Thanks for your patience.
All feedback of the application is more than welcome. Thanks
