### ISSUE TITLE
Snap clients don't get their configured names

### ISSUE THREAD

**Issue by sprnza** [cristianpb/muse#5]
I've changed names of snapclients and they appears displayed correctly in Android Snapclient, but in Muse they keep being displayed with their ServerID. See attached file. The issue is the name of an Android Client which doesn't support its ServerID being set gets all available width of the popup. So I'm unable to adjust volume level.
![19-05-2020-10:09:54-scrot](https://user-images.githubusercontent.com/1968839/82295928-1e070f00-99b9-11ea-81d5-307bcc2e4c7b.jpg)

**Comment by cristianpb** [comment]
Hi @sprnza 
Thanks for pointing that out. I will make some improvements:
- Add the possibility to set the name of a client in Muse
- Show a short version of the name. 
- Hear of changes in snapcast so that clients and groups id get updated when they are changed in a place different that Muse

**Comment by sprnza** [comment]
Yay! It would be great! Thanks for the project btw!

**Comment by cristianpb** [comment]
Version v0.0.14 is out.

I did some improvements to display of the group and clients names to avoid problems with long names.
There is also the possibility to edit snapcast clients and groups name:
* On desktop: there is a button on top right of the snapcast clients window.
* On mobile: There is a button on the down navigation bar. It's left to the random playback button.

Would you mind to test this version ?

**Comment by sprnza** [comment]
Yep. Works flawlessly. Thanks!
