### ISSUE TITLE
Unable to add the whole album to the playlist

### ISSUE THREAD

**Issue by sprnza** [cristianpb/muse#6]
Hi there!
I've stumbled upon an issue when I'm unable to add the whole album to the playlist. If I click the little arrow on an album it opens up and there is no option to "Play" or "Add to queue". Or maybe I don't know where to look for these options.
![23-05-2020-09:01:55-scrot](https://user-images.githubusercontent.com/1968839/82723009-22db0400-9cd4-11ea-9835-117e28562d8f.jpg)

**Comment by sprnza** [comment]
I was expecting clicking on an album name opens it content and clicking on the arrow opens up options to play the whole album. Please correct me if I'm wrong.

**Comment by cristianpb** [comment]
Hi @sprnza 
Thanks again for your feedback, you are totally right.

I just released version 0.0.15 with a fix for this issue. Now your are able to play albums or artists in the browser page. 

I also added some small improvements and the possibility to create and edit snapcast groups using drag and drop in the settings page. 

Would you mind to test that ?

**Comment by sprnza** [comment]
Hi @cristianpb! After update to 0.0.15 the arrow is missing on Artists and Albums.
![24-05-2020-10:19:46-scrot](https://user-images.githubusercontent.com/1968839/82748120-28a21980-9da8-11ea-8559-1dd11de129bd.jpg)

![24-05-2020-10:20:55-scrot](https://user-images.githubusercontent.com/1968839/82748141-48394200-9da8-11ea-972b-644883d067a0.jpg)

**Comment by cristianpb** [comment]
Which extensions are you using ? What is your output for `pip3 list |grep Mopidy` ? Are you browsing using Mopidy-Local ?
There must be something different from what I have in my local environment :thinking:

**Comment by sprnza** [comment]
```
➜  ~ pip3 list |grep Mopidy 
Mopidy                    3.0.2      
Mopidy-MPD                3.0.0      
Mopidy-Muse               0.0.15     
Mopidy-MusicBox-Webclient 3.1.0      
Mopidy-Subidy             1.0.0  
```
Mopidy-MusicBox-Webclient is disabled in the mopidy conifg. I;m browsing using Mopidy-Subidy. I could share access to my subsonic instance if you'd like.

**Comment by sprnza** [comment]
I've sent a link to my subsonic instance to email shown in your CV.

**Comment by cristianpb** [comment]
Release v0.0.16 is out  :rocket: 

I think it should work now. In addition now there should be a dropdown button to play all the tracks of an album.

**Comment by sprnza** [comment]
Yep, works like a bomb! Thanks a lot!
