### ISSUE TITLE
Play all from search results doesn't do anything

### ISSUE THREAD

**Issue by sprnza** [cristianpb/muse#8]
Hi there!
If I click "Play all" from the search results playlist is being cleared and nothing being played. "Add to queue" and "Shuffle & Play All" works correctly.

**Comment by cristianpb** [comment]
Hi,
Thanks again for the bug report.
I just released v0.0.17 with that fix and some other small stuff.

**Comment by sprnza** [comment]
Hi! Thanks! fixed!
